# Generated by Django 4.2.1 on 2023-05-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrient',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
