# Generated by Django 4.2.1 on 2023-06-05 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_alter_nutrient_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(choices=[('H', 'Hydroponics'), ('CS', 'Clay Soil'), ('LS', 'Loam Soil'), ('SS', 'Sandy Soil')], default='CS', max_length=2)),
                ('stage', models.CharField(choices=[('VS', 'vegitation Stage'), ('FS', 'Fruiting Stage')], default='VS', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
